src/objects/VacationRequest__c.object
<CustomObject>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Vacation_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Vacation Request</label>
    <nameField>
        <label>Vacation Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vacation Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

test-vacationrequest/src/classes/requestListItemController.cls
public class requestListItemController {
	// show Remove and Submit Buttons
	@AuraEnabled(cacheable=true)
	public static Boolean showRemoveSubmit(VacationRequest__c vr) {
	if (vr.Status__c == 'New' && vr.CreatedById == UserInfo.getUserId())
		return true;
	else
		return false;
	}

	// show Approve Button
	@AuraEnabled(cacheable=true)
	public static Boolean showApprove(VacationRequest__c vr) {
		if (vr.Status__c == 'Submitted' && vr.Manager__r.Id == UserInfo.getUserId())
			return true;
		else
			return false;
	}

	// Remove record
	@AuraEnabled
	public static void vrRemove(VacationRequest__c vrToRemove) {
		delete vrToRemove;
	}

	// Submit record
	@AuraEnabled
	public static void vrSubmit(VacationRequest__c vrToSubmit) {
		vrToSubmit.Status__c = 'Submitted';
		update vrToSubmit;
	}

	// Approve record
	@AuraEnabled
	public static void vrApprove(VacationRequest__c vrToApprove) {
		vrToApprove.Status__c = 'Approved';
		update vrToApprove;
	}

	// get background color of a request based on Status
	@AuraEnabled(cacheable=true)
	public static String getColor(String Status) {
		return Status.toLowerCase()+'-color';
	}
}