src/objects/VacationRequest__c.object
<CustomObject>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>EndDate</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Vacation_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestType__c</fullName>
        <label>RequestType</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Vacation</fullName>
                </value>
                <value>
                    <fullName>Sick</fullName>
                </value>
                <value>
                    <fullName>Unpaid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>StartDate</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WorkingDays__c</fullName>
        <label>WorkingDays</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Vacation Request</label>
    <nameField>
        <label>Vacation Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vacation Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/vrController.cls
public class vrController {
	@AuraEnabled(cacheable=true)
	public static List<VacationRequest__c> getRequestList() {
		return [
				SELECT Id, Name, CreatedBy.Name, RequestType__c, StartDate__c, EndDate__c, WorkingDays__c, Status__c, Manager__r.Name
				FROM VacationRequest__c
		];
	}

	@AuraEnabled(cacheable=true)
	public static List<VacationRequest__c> getOnlyMyList() {
		return [
				SELECT Id, CreatedById, CreatedBy.Name, RequestType__c, StartDate__c, EndDate__c, WorkingDays__c, Status__c, Manager__r.Name
				FROM VacationRequest__c
				WHERE CreatedById=:UserInfo.getUserId()
		];
	}

	@AuraEnabled(cacheable=true)
	public static String NoManager() {
		User managerId = [
				SELECT Id, ManagerId
				FROM User
				WHERE Id=:UserInfo.getUserId()
		];
		if (managerId.ManagerId == null) {
			return null;
		}
		return managerId.ManagerId;
	}

	@AuraEnabled(cacheable=true)
	public static Integer CalculateWorkingDays (Date StartDate, Date EndDate) {
		Integer workingDays = 0;

		for(integer i=0; i <= startDate.daysBetween(endDate); i++) {
			Date dt = startDate + i;
			DateTime currDate = DateTime.newInstance(dt.year(), dt.month(), dt.day());
			String todayDay = currDate.format('EEEE');
			if(todayDay != 'Saturday' && todayDay !='Sunday') {
				workingDays = workingDays + 1;
			}
		}
		return workingDays;
	}

	@AuraEnabled
	public static void vrRemove(String vrName) {
		VacationRequest__c vrToRemove = [
				SELECT Name
				FROM VacationRequest__c
				WHERE Name =: vrName];
		delete vrToRemove;
	}

	@AuraEnabled
	public static void vrSubmit(String vrName) {
		VacationRequest__c vrToSubmit = [
				SELECT Name, Status__c
				FROM VacationRequest__c
				WHERE Name =: vrName];
		vrToSubmit.Status__c = 'Submitted';
		 update vrToSubmit;
	}

	@AuraEnabled
	public static void vrApprove(String vrName) {
		VacationRequest__c vrToApprove = [
				SELECT Name, Status__c
				FROM VacationRequest__c
				WHERE Name =: vrName];
		vrToApprove.Status__c = 'Approved';
		update vrToApprove;
	}

	@AuraEnabled(cacheable=true)
	public static String getUserId() {
		return UserInfo.getUserId();
	}
}